# Generated by Django 2.0.6 on 2018-06-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'verbose_name_plural': 'Women'},
        ),
    ]
